services:
  - type: web
    name: movie-api
    env: python
    plan: free
    region: singapore  # or singapore, frankfurt, etc.
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviepage.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: moviepage.settings  # ‚Üê Changed to match startCommand

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString

databases:
  - name: movie-db
    plan: free
    region: singapore  # Should match web service region