services:
  - type: web
    name: movie-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviepage.wsgi:application"  # ✅ Correct
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: moviepage.settings  # ✅ Matches wsgi.py

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString

databases:
  - name: movie-db
    plan: free