services:
  - type: web
    name: moviepage
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviepage.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviepage-db
          property: connectionString

databases:
  - name: moviepage-db
    databaseName: moviepage
    user: movieuser
